apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: gonamespace
spec:
  type: NodePort
  selector:
    app: go-app
  ports:
    - port: 8080
      targetPort: 8010
      nodePort: 32121
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: gonamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      name: go-pod
      labels:
        app: go-app
    spec:
      containers:
        - name: go-container
          image: 392133049967.dkr.ecr.ap-northeast-1.amazonaws.com/sudip-27may-repo:mygoapp
          ports:
            - containerPort: 8010
